class Mechanic {
 final String name;
  final String imageUrl;
  final String expertise;
  final String phone;
  final String distance;
  final String vehicleType;
  final List<String> issues;

  Mechanic({
    required this.name,
    required this.expertise,
    required this.distance,
    required this.vehicleType,
    required this.issues, 
    required this.phone,
    required this.imageUrl,
  });
}

List<Mechanic> allMechanics = [
  Mechanic(
    name: "Ahmed Raza",
    expertise: "Puncture",
    phone: "03111234567",
    distance: "1.2 km away",
    vehicleType: "Car",
    imageUrl: "https://i.pravatar.cc/150?img=1",
    issues: ["Puncture", "Tire Change"],
  ),
  Mechanic(
    name: "Ali Khan",
    expertise: "Tire Change",
    phone: "03112234567",
    distance: "3.5 km away",
    vehicleType: "Bike",
    imageUrl: "https://i.pravatar.cc/150?img=2",
    issues: ["Tire Change"],
  ),
  Mechanic(
    name: "Usman Tariq",
    expertise: "Flat Tire",
    phone: "03113234567",
    distance: "2.8 km away",
    vehicleType: "Truck",
    imageUrl: "https://i.pravatar.cc/150?img=3",
    issues: ["Flat Tire", "Puncture"],
  ),
  Mechanic(
    name: "Bilal Ahmed",
    expertise: "Air Refill",
    phone: "03114234567",
    distance: "4.2 km away",
    vehicleType: "Suzuki",
    imageUrl: "https://i.pravatar.cc/150?img=4",
    issues: ["Air Refill"],
  ),
  Mechanic(
    name: "Zeeshan Akram",
    expertise: "Puncture",
    phone: "03115234567",
    distance: "5.1 km away",
    vehicleType: "Car",
    imageUrl: "https://i.pravatar.cc/150?img=5",
    issues: ["Puncture"],
  ),
  Mechanic(
    name: "Waqas Javed",
    expertise: "Tire Change",
    phone: "03116234567",
    distance: "1.9 km away",
    vehicleType: "Bike",
    imageUrl: "https://i.pravatar.cc/150?img=6",
    issues: ["Tire Change", "Flat Tire"],
  ),
  Mechanic(
    name: "Imran Siddiqui",
    expertise: "Flat Tire",
    phone: "03117234567",
    distance: "2.1 km away",
    vehicleType: "Truck",
    imageUrl: "https://i.pravatar.cc/150?img=7",
    issues: ["Flat Tire"],
  ),
  Mechanic(
    name: "Saad Qureshi",
    expertise: "Air Refill",
    phone: "03118234567",
    distance: "6.0 km away",
    vehicleType: "Suzuki",
    imageUrl: "https://i.pravatar.cc/150?img=8",
    issues: ["Air Refill", "Puncture"],
  ),
  Mechanic(
    name: "Hassan Rauf",
    expertise: "Puncture",
    phone: "03119234567",
    distance: "0.9 km away",
    vehicleType: "Car",
    imageUrl: "https://i.pravatar.cc/150?img=9",
    issues: ["Puncture", "Air Refill"],
  ),
  Mechanic(
    name: "Faizan Ali",
    expertise: "Tire Change",
    phone: "03110234567",
    distance: "3.0 km away",
    vehicleType: "Bike",
    imageUrl: "https://i.pravatar.cc/150?img=10",
    issues: ["Tire Change"],
  ),
  Mechanic(
    name: "Noman Asif",
    expertise: "Flat Tire",
    phone: "03111334567",
    distance: "2.4 km away",
    vehicleType: "Truck",
    imageUrl: "https://i.pravatar.cc/150?img=11",
    issues: ["Flat Tire", "Tire Change"],
  ),
  Mechanic(
    name: "Salman Yousuf",
    expertise: "Air Refill",
    phone: "03112434567",
    distance: "3.7 km away",
    vehicleType: "Suzuki",
    imageUrl: "https://i.pravatar.cc/150?img=12",
    issues: ["Air Refill"],
  ),
  Mechanic(
    name: "Junaid Haroon",
    expertise: "Puncture",
    phone: "03113534567",
    distance: "1.1 km away",
    vehicleType: "Car",
    imageUrl: "https://i.pravatar.cc/150?img=13",
    issues: ["Puncture"],
  ),
  Mechanic(
    name: "Owais Farooqi",
    expertise: "Tire Change",
    phone: "03114634567",
    distance: "4.4 km away",
    vehicleType: "Bike",
    imageUrl: "https://i.pravatar.cc/150?img=14",
    issues: ["Tire Change", "Flat Tire"],
  ),
  Mechanic(
    name: "Tariq Mehmood",
    expertise: "Flat Tire",
    phone: "03115734567",
    distance: "5.9 km away",
    vehicleType: "Truck",
    imageUrl: "https://i.pravatar.cc/150?img=15",
    issues: ["Flat Tire"],
  ),
  Mechanic(
    name: "Fahad Latif",
    expertise: "Air Refill",
    phone: "03116834567",
    distance: "3.3 km away",
    vehicleType: "Suzuki",
    imageUrl: "https://i.pravatar.cc/150?img=16",
    issues: ["Air Refill", "Tire Change"],
  ),
  Mechanic(
    name: "Adnan Mirza",
    expertise: "Puncture",
    phone: "03117934567",
    distance: "2.0 km away",
    vehicleType: "Car",
    imageUrl: "https://i.pravatar.cc/150?img=17",
    issues: ["Puncture"],
  ),
  Mechanic(
    name: "Rizwan Sheikh",
    expertise: "Tire Change",
    phone: "03118034567",
    distance: "3.6 km away",
    vehicleType: "Bike",
    imageUrl: "https://i.pravatar.cc/150?img=18",
    issues: ["Tire Change"],
  ),
  Mechanic(
    name: "Shahbaz Nadeem",
    expertise: "Flat Tire",
    phone: "03119134567",
    distance: "1.4 km away",
    vehicleType: "Truck",
    imageUrl: "https://i.pravatar.cc/150?img=19",
    issues: ["Flat Tire", "Puncture"],
  ),
  Mechanic(
    name: "Zubair Khan",
    expertise: "Air Refill",
    phone: "03110334567",
    distance: "4.7 km away",
    vehicleType: "Suzuki",
    imageUrl: "https://i.pravatar.cc/150?img=20",
    issues: ["Air Refill"],
  ),
];
